FILES = utility.py \
	transform.py \
	manipblty.py \
	Quaternion.py \
	jacobian.py \
	trajectory.py \
	kinematics.py \
	dynamics.py \
	Link.py \
	Robot.py \
	plot.py \
	puma560.py \
	puma560akb.py \
	stanford.py \
	phantomx.py \
	twolink.py \
	fourlink2d.py \
	fourlink3d.py \
	parsedemo.py \
	testparser.py

doc: $(FILES)
	epydoc $(FILES)
